import org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodArgumentResolver;
public class FunctionUse1191 {
public void funcUse() {
AbstractMessageConverterMethodArgumentResolver abstractmessageconvertermethodargumentresolver = new AbstractMessageConverterMethodArgumentResolver();
abstractmessageconvertermethodargumentresolver.getAllSupportedMediaTypes(null);
}
}