import org.springframework.web.servlet.support.AbstractAnnotationConfigDispatcherServletInitializer;
public class FunctionUse549 {
public void funcUse() {
AbstractAnnotationConfigDispatcherServletInitializer abstractannotationconfigdispatcherservletinitializer = new AbstractAnnotationConfigDispatcherServletInitializer();
abstractannotationconfigdispatcherservletinitializer.getServletConfigClasses();
}
}