import org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMethodMappingNamingStrategy;
public class FunctionUse1386 {
public void funcUse() {
RequestMappingInfoHandlerMethodMappingNamingStrategy requestmappinginfohandlermethodmappingnamingstrategy = new RequestMappingInfoHandlerMethodMappingNamingStrategy();
requestmappinginfohandlermethodmappingnamingstrategy.getName(null,null);
}
}